FROM grpc/python

RUN pip install -U pip
RUN pip install numpy

ADD ./FullScriptSupport /app
ADD ./Generated /app

WORKDIR /app
ENTRYPOINT ["python"]
CMD ["ExtensionService_Script.py"]
EXPOSE 50051


